global_settings:
  default_save_dir: "/home/alex/Nextcloud/Projects/Rate-of-Profit-Paper/assets"
model_specific_settings:
  wright-cross-dual-3-commodity:
    commodity_names: ["Corn", "Iron", "Sugar"]
  morishima_disproportionality_reinvestment:
demos: 
  wright-cross-dual-3-commodity:
    name: "Wright's Cross-Dual Disequilibrium Model (Three Commodities)"
    desc: Starting parameters are based on the example in Wright's PhD thesis. See the GitHub wiki pages for detailed information.
    default: True
    details:
      simulation_model: wright-cross-dual-3-commodity
      simulation_function: simulate
      starting_plots: prices_and_values
      default_preset: default_preset
      starting_lims: [[0.0, 100.0],[0.0, 12.0]]
  morishima_disproportionality_reinvestment:
    name: "Morishima's Material Constrained Reinvestment Model"
    desc: See GitHub wiki pages for detailed information.
    details:
      simulation_model: morishima_disproportionality_reinvestment
      simulation_function: get_trajectories
      default_preset: nice_example
      starting_lims: [[0, 14],[-500,1600]]

